---
- name: Http | Intalling Http client library 
  pip:
    name: httplib2
#- name: General | Installing general tools
#  action: yum pkg={{ item }} state=installed
#  with_items:
#    - xauth
#    - gedit

- name: Containers | Installing dockers
  action: yum pkg={{ item }} state=installed
  with_items:
    - docker
    - docker-logrotate

- name: Cluster Orchestrator | Installing kubernetes
  action: yum pkg={{ item }} state=installed
  with_items:
    - kubernetes
    - etcd
    - flannel

- name: Configure kubernetes
  copy: src=kubernetes_config dest=/etc/kubernetes/config mode=0664

- name: Configure ETCD Service
  copy: src=etcd_config dest=/etc/etcd/etcd.conf mode=0664

- name: Configure Flannel Service
  copy: src=flannel_conf dest=/etc/sysconfig/flanneld mode=0664

- name: Build hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].inventory_hostname }} {{ hostvars[item].ansible_host }} {{ hostvars[item].ansible_host }}.com"
    state: present
  with_items: "{{ groups.all }}"
